import type { MyIssue } from '../types';

// วันนี้ (mock) = 2026-07-14 — dueDate ก่อนหน้านี้ + ยังไม่ done ถือว่าเกินกำหนด
export const mockIssues: MyIssue[] = [
  {
    id: 'i-01',
    key: 'ORB-142',
    title: 'แก้ layout หน้า Dashboard เพี้ยนบนจอ 1366px',
    projectId: 'orbit-web',
    status: 'in_progress',
    priority: 'urgent',
    dueDate: '2026-07-13',
    updatedAt: '2026-07-14',
  },
  {
    id: 'i-02',
    key: 'ORB-139',
    title: 'เพิ่ม empty state ให้หน้า Audit Logs',
    projectId: 'orbit-web',
    status: 'in_review',
    priority: 'high',
    dueDate: '2026-07-16',
    updatedAt: '2026-07-13',
  },
  {
    id: 'i-03',
    key: 'ATL-87',
    title: 'Push notification ไม่เด้งบน Android 15',
    projectId: 'atlas-mobile',
    status: 'todo',
    priority: 'urgent',
    dueDate: '2026-07-15',
    updatedAt: '2026-07-12',
  },
  {
    id: 'i-04',
    key: 'NOV-231',
    title: 'Rate limit endpoint /auth/refresh',
    projectId: 'nova-api',
    status: 'in_progress',
    priority: 'high',
    dueDate: '2026-07-15',
    updatedAt: '2026-07-14',
  },
  {
    id: 'i-05',
    key: 'ORB-131',
    title: 'ปรับ contrast ของ muted text ใน dark mode ให้ผ่าน AA',
    projectId: 'orbit-web',
    status: 'todo',
    priority: 'medium',
    dueDate: '2026-07-20',
    updatedAt: '2026-07-11',
  },
  {
    id: 'i-06',
    key: 'LUM-45',
    title: 'ออกแบบ icon set สำหรับเมนู Admin ชุดใหม่',
    projectId: 'lumen-design',
    status: 'in_review',
    priority: 'medium',
    dueDate: '2026-07-18',
    updatedAt: '2026-07-13',
  },
  {
    id: 'i-07',
    key: 'NOV-228',
    title: 'Migration: เพิ่ม index ให้ตาราง audit_logs',
    projectId: 'nova-api',
    status: 'todo',
    priority: 'high',
    dueDate: '2026-07-12',
    updatedAt: '2026-07-10',
  },
  {
    id: 'i-08',
    key: 'ATL-82',
    title: 'รองรับ deep link เข้าหน้ารายละเอียดโปรเจกต์',
    projectId: 'atlas-mobile',
    status: 'in_progress',
    priority: 'medium',
    dueDate: '2026-07-22',
    updatedAt: '2026-07-14',
  },
  {
    id: 'i-09',
    key: 'ORB-127',
    title: 'เขียน unit test ให้ apiFetch (กรณี refresh ชนกัน)',
    projectId: 'orbit-web',
    status: 'done',
    priority: 'medium',
    dueDate: '2026-07-10',
    updatedAt: '2026-07-10',
  },
  {
    id: 'i-10',
    key: 'LUM-41',
    title: 'สรุป design tokens สี semantic รอบสอง',
    projectId: 'lumen-design',
    status: 'todo',
    priority: 'low',
    updatedAt: '2026-07-09',
  },
  {
    id: 'i-11',
    key: 'NOV-219',
    title: 'เอกสาร API v2: ตัวอย่าง response ของ error codes',
    projectId: 'nova-api',
    status: 'done',
    priority: 'low',
    dueDate: '2026-07-08',
    updatedAt: '2026-07-08',
  },
  {
    id: 'i-12',
    key: 'ATL-79',
    title: 'ลด bundle size ของ splash screen (ตอนนี้ 4.2MB)',
    projectId: 'atlas-mobile',
    status: 'in_review',
    priority: 'high',
    dueDate: '2026-07-17',
    updatedAt: '2026-07-13',
  },
  {
    id: 'i-13',
    key: 'ORB-118',
    title: 'ปุ่ม export CSV ในหน้า Login Logs',
    projectId: 'orbit-web',
    status: 'todo',
    priority: 'low',
    dueDate: '2026-07-28',
    updatedAt: '2026-07-07',
  },
  {
    id: 'i-14',
    key: 'LUM-38',
    title: 'Motion spec: ความเร็ว transition มาตรฐานของ modal',
    projectId: 'lumen-design',
    status: 'done',
    priority: 'medium',
    dueDate: '2026-07-05',
    updatedAt: '2026-07-05',
  },
];
