import {
  Activity,
  BadgeCheck,
  Bell,
  Briefcase,
  Building,
  Calendar,
  CircleDot,
  Component,
  FileText,
  Fingerprint,
  FolderKanban,
  Inbox,
  Key,
  LayoutDashboard,
  ListTodo,
  MapPin,
  Megaphone,
  Menu,
  MessageSquare,
  Settings,
  Shield,
  ShieldAlert,
  Users,
  Users2,
  PenLine,
  Radar,
  CircleQuestionMark as CircleQuestion,
  type LucideIcon,
} from 'lucide-react';

const registry: Record<string, LucideIcon> = {
  Activity,
  BadgeCheck,
  Bell,
  Briefcase,
  Building,
  Calendar,
  CircleDot,
  Component,
  FileText,
  Fingerprint,
  FolderKanban,
  Inbox,
  Key,
  LayoutDashboard,
  ListTodo,
  MapPin,
  Megaphone,
  Menu,
  MessageSquare,
  Settings,
  Shield,
  ShieldAlert,
  Users,
  Users2,
  PenLine,
  Radar,
  CircleQuestion,
};

export function resolveIcon(name: string | null | undefined): LucideIcon {
  if (!name) return CircleDot;
  return registry[name] ?? CircleDot;
}
